#!/usr/bin/env bash
# Write a Bash script that displays:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash is displayed (refer to the example)
currDir=$(ls ./)
for eachfile in $currDir
do
	cut -d "-" -f2- <<< "$eachfile"
done
